### ISSUE TITLE
32x16 panel

### ISSUE THREAD

**Issue by paccerdk** [VGottselig/ESP32-RGB-Matrix-Display#12]
The lower half of the screen is bugged through all the demos (looks like random memory?)
I've only changed 
```
#define COLUMNS 32
#define ROWS 16
```

Interestingly enough, changing ROWS to 32 fills the whole display - but of course cuts/renders graphics out side of screen

Here's a video:
[video_2018-08-20_00-02-16.zip](https://github.com/VGottselig/ESP32-RGB-Matrix-Display/files/2300708/video_2018-08-20_00-02-16.zip)

The connector is as follows:

R1 | G1
B1 | GND
R2 | G2
B2 | GND
A | B
C | NC
CLK | STB/LAT
OE | GND

I purchased it from here:
https://www.aliexpress.com/item/Free-shipping-2016-Coreman-192X96mm-32X16-pixels-p6-led-display-module-Whole-seller-Factory-Price-p6/1000001365724.html

_Originally posted by @paccerdk in https://github.com/VGottselig/ESP32-RGB-Matrix-Display/issues/4#issuecomment-414160029_

**Comment by wavewolf** [comment]
could you run this library in a matrix 16x32 rgb?

**Comment by paccerdk** [comment]
Currently dont have access to 16x32 matrix, closing old issue
